[package]
name = "rdbc"
description = "Rust DataBase Connectivity (RDBC) API"
version = "0.1.6"
authors = ["Andy Grove <andygrove73@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
async-trait = "0.1.22"
futures = "0.3.1"
tokio = { version="0.2.9", features=["full"] }
